In [76]:
import numpy as np

In [77]:
arr_1 = np.random.randint(1,10, size=(3,1))
arr_2 = np.random.randint(10,20, size=(3))

In [78]:
print(arr_1)

[[5]
 [1]
 [9]]


In [79]:
print(arr_2)

[19 11 13]


In [80]:
arr_1 + arr_2


array([[24, 16, 18],
       [20, 12, 14],
       [28, 20, 22]])

Если одна матрица имеет размер 1 в какой-то оси, её можно «растянуть» до нужного размера другой матрицы, чтобы сложение стало возможным.

**Пример:**

- Матрица 3×1:
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}

- Матрица 3×4:


\begin{bmatrix}
a & b & c & d \\
e & f & g & h \\
i & j & k & l
\end{bmatrix}

Мы можем «растянуть» 3×1 в 3×4:


\begin{bmatrix}
1 & 1 & 1 & 1 \\
2 & 2 & 2 & 2 \\
3 & 3 & 3 & 3
\end{bmatrix}

Теперь сложение можно выполнить покомпонентно.