In [3]:
import pandas as pd
import numpy as np

arr = np.arange(20).reshape(2, 5, 2)

print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [4]:
print(arr[1:2, 2:5, :])

[[[14 15]
  [16 17]
  [18 19]]]


In [35]:
arr3 = np.arange(100).astype(np.int8).reshape(10,10)
print(arr3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [47]:
arr0 = np.empty(100).astype(np.int8).reshape(10,10)
np.fill_diagonal(arr0, np.diagonal(arr3))
np.fill_diagonal(np.fliplr(arr0), np.fliplr(arr3).diagonal())

print("arr3:")
print(arr3)

print("\narr0:")
print(arr0)

arr3:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

arr0:
[[ 0  0  0  0  0  0  0  0  0  9]
 [ 0 11  0  0  0  0  0  0 18  0]
 [ 0  0 22  0  0  0  0 27  0  0]
 [ 0  0  0 33  0  0 36  0  0  0]
 [ 0  0  0  0 44 45  0  0  0  0]
 [ 0  0  0  0 54 55  0  0  0  0]
 [ 0  0  0 63  0  0 66  0  0  0]
 [ 0  0 72  0  0  0  0 77  0  0]
 [ 0 81  0  0  0  0  0  0 88  0]
 [90  0  0  0  0  0  0  0  0 99]]


In [48]:
print(arr3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [50]:
main_diag = np.diag(arr3)
anti_diag = np.diag(np.fliplr(arr3))

In [53]:
np.concatenate((main_diag,anti_diag))

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99,  9, 18, 27, 36, 45, 54, 63,
       72, 81, 90], dtype=int8)