# NumPy Array Exercises


This notebook contains a set of exercises to help you practice creating, manipulating, 
and analyzing arrays using NumPy. These exercises are inspired by content on basic and advanced 
NumPy array operations. Try completing each exercise below.


### Exercise 1: Create an Array of Zeros
Create a 1D array of 10 zeros using NumPy.

In [19]:
import numpy as np

In [20]:
# Write your code here
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise 2: Create an Array of Ones
Create a 1D array of 5 ones using NumPy.

In [21]:
# Write your code here
np.ones(5)

array([1., 1., 1., 1., 1.])

### Exercise 3: Identity Matrix
Create a 3x3 identity matrix using NumPy.

In [22]:
# Write your code here
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Exercise 4: Generate Linearly Spaced Array
Generate an array with 10 values evenly spaced between 0 and 1.

In [23]:
# Write your code here
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Exercise 5: Reshape Array
Reshape a 1D array of 9 elements into a 3x3 matrix.

In [24]:
# Write your code here
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 6: Array Slicing
Create a 1D array with values from 0 to 9 and slice it to get only even values.

In [25]:
# Write your code here
arr = np.arange(9)
even = arr[arr % 2 == 0]
even

array([0, 2, 4, 6, 8])

### Exercise 7: Calculate Mean
Create a 1D array with values from 1 to 10 and find its mean.

In [26]:
# Write your code here
arr = np.arange(1, 11)
print(f"Mean: {np.mean(arr)}")

Mean: 5.5


### Exercise 8: Calculate Standard Deviation
Generate an array of 5 random values and calculate the standard deviation.

In [27]:
# Write your code here

arr = (np.random.rand(5) * 100).astype(dtype=int)
std = np.std(arr)

print(f"Array: {arr}\n"
      f"Std: {std}")




Array: [65 14 85 85  8]
Std: 33.838439680339874


### Exercise 9: Filter Values
Create a 1D array of integers from 1 to 10 and filter out values greater than 5.

In [28]:
# Write your code here

arr = np.arange(1, 11)
arr = arr[arr > 5]
arr

array([ 6,  7,  8,  9, 10])

### Exercise 10: Replace Values Based on Condition
Generate a random array of 10 integers between 1 and 100, and replace values greater than 50 with 50.

In [29]:
# Write your code here
arr = np.random.randint(1, 101, 10)
print(f"Before: {arr}")
arr[arr > 50] = 50
print(f"After:  {arr}")



Before: [31 69 54 24 57 21 87 61  2 16]
After:  [31 50 50 24 50 21 50 50  2 16]


### Exercise 11: Stack Arrays
Create two 1D arrays of 5 elements each and stack them vertically.

In [30]:
# Write your code here
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

stacked = np.vstack((a, b))
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Exercise 12: Element-wise Operations
Create two 1D arrays of 3 elements each and perform element-wise addition.

In [31]:
# Write your code here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

### Exercise 13: Generate Random Integers
Generate an array of 10 random integers between 1 and 50.

In [32]:
# Write your code here

### Exercise 14: Random Normal Distribution
Generate a 1D array of 7 random values from a standard normal distribution.

In [33]:
# Write your code here

In [36]:
%%time

arr = np.arange(1_000_000, dtype=np.uint64)
arr = arr ** 2 + arr ** 5 + arr
arr

CPU times: user 4.98 ms, sys: 1.85 ms, total: 6.83 ms
Wall time: 5.23 ms


array([                  0,                   3,                  38, ...,
       9679979971473158931, 6592479144603745570, 5058114244274780415],
      dtype=uint64)

In [37]:
np.save("numpy_Arr", arr)