In [2]:
import numpy as np

In [29]:
np.empty((2,2,2))

array([[[1.56433576, 0.40584858],
        [0.63327464, 0.73634205]],

       [[1.29635375, 1.20510054],
        [1.01112465, 0.45296395]]])

In [31]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [3]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [13]:
np.linspace(1, 9, 5)

array([1., 3., 5., 7., 9.])

In [18]:
np.logspace(1, 2, 4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [25]:
arr_randn = np.random.randn(1000) # c нормализацией
arr_rand = np.random.rand(1000)


array([[[ 0.04147153, -0.32041401,  2.36680378],
        [-1.23621763,  1.06333024,  0.04486206]],

       [[ 0.40016749, -0.79861445,  1.15096037],
        [-0.28631923, -2.31212322,  0.36716656]]])

In [28]:
np.random.randint(0,10,size=(5,5))

array([[5, 8, 9, 2, 7],
       [7, 1, 8, 2, 2],
       [2, 5, 9, 9, 6],
       [1, 5, 5, 6, 6],
       [2, 7, 9, 6, 6]])